runtime: nodejs16
service: team2
service_account: 'line_taken_down_for_account_protection'
env: standard
env_variables:
  REDIS_URL: "redis://line_taken_down_for_account_protection"
instance_class: F4
inbound_services:
- warmup
automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 1
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: 80ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
